// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: message.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteMessageReaction = `-- name: DeleteMessageReaction :exec
DELETE FROM message_reactions
WHERE message_id = ? AND user_id = ? AND emoji = ?
`

type DeleteMessageReactionParams struct {
	MessageID []byte
	UserID    []byte
	Emoji     string
}

func (q *Queries) DeleteMessageReaction(ctx context.Context, arg DeleteMessageReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const getAttachmentsByMessageIDs = `-- name: GetAttachmentsByMessageIDs :many
SELECT id, message_id, file_name, file_url,
    mime_type, file_size_bytes, width, height,
    duration_sec, created_at
FROM attachments
WHERE message_id IN (/*SLICE:message_ids*/?)
ORDER BY created_at ASC
`

func (q *Queries) GetAttachmentsByMessageIDs(ctx context.Context, messageIds [][]byte) ([]Attachment, error) {
	query := getAttachmentsByMessageIDs
	var queryParams []interface{}
	if len(messageIds) > 0 {
		for _, v := range messageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(messageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.FileUrl,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.Width,
			&i.Height,
			&i.DurationSec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxSeq = `-- name: GetMaxSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS UNSIGNED) AS max_seq
FROM messages
WHERE conversation_id = ?
`

// Xử lý conversation chưa có message (NULL → 0).
func (q *Queries) GetMaxSeq(ctx context.Context, conversationID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxSeq, conversationID)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, sender_id, parent_id, type,
       content, content_encrypted, iv, seq,
       is_edited, is_deleted, deleted_at, created_at, updated_at
FROM messages
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id []byte) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.ParentID,
		&i.Type,
		&i.Content,
		&i.ContentEncrypted,
		&i.Iv,
		&i.Seq,
		&i.IsEdited,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageCursorTS = `-- name: GetMessageCursorTS :one
SELECT created_at
FROM messages
WHERE id = ? AND conversation_id = ?
LIMIT 1
`

type GetMessageCursorTSParams struct {
	ID             []byte
	ConversationID []byte
}

func (q *Queries) GetMessageCursorTS(ctx context.Context, arg GetMessageCursorTSParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getMessageCursorTS, arg.ID, arg.ConversationID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getReactionsByMessageIDs = `-- name: GetReactionsByMessageIDs :many
SELECT id, message_id, user_id, emoji , created_at
FROM message_reactions 
WHERE message_id IN (/*SLICE:message_ids*/?)
ORDER BY created_at ASC
`

func (q *Queries) GetReactionsByMessageIDs(ctx context.Context, messageIds [][]byte) ([]MessageReaction, error) {
	query := getReactionsByMessageIDs
	var queryParams []interface{}
	if len(messageIds) > 0 {
		for _, v := range messageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(messageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageReaction{}
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCountByWatermark = `-- name: GetUnreadCountByWatermark :one
SELECT COUNT(*) AS count
FROM   messages        m
JOIN   conversation_members cm
         ON  cm.conversation_id = m.conversation_id
         AND cm.user_id         = ?
WHERE  m.conversation_id = ?
  AND  m.sender_id       != ?
  AND  m.is_deleted      = 0
  AND  (cm.last_read_at IS NULL OR m.created_at > cm.last_read_at)
`

type GetUnreadCountByWatermarkParams struct {
	UserID         []byte
	ConversationID []byte
	SenderID       []byte
}

func (q *Queries) GetUnreadCountByWatermark(ctx context.Context, arg GetUnreadCountByWatermarkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCountByWatermark, arg.UserID, arg.ConversationID, arg.SenderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO attachments
    (id, message_id, file_name, file_url, mime_type,
     file_size_bytes, width, height, duration_sec)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAttachmentParams struct {
	ID            []byte
	MessageID     []byte
	FileName      string
	FileUrl       string
	MimeType      string
	FileSizeBytes uint64
	Width         sql.NullInt32
	Height        sql.NullInt32
	DurationSec   sql.NullInt16
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, insertAttachment,
		arg.ID,
		arg.MessageID,
		arg.FileName,
		arg.FileUrl,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.Width,
		arg.Height,
		arg.DurationSec,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages
    (id, conversation_id, sender_id, parent_id, type,
     content, content_encrypted, iv, seq)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID               []byte
	ConversationID   []byte
	SenderID         []byte
	ParentID         sql.NullString
	Type             int8
	Content          sql.NullString
	ContentEncrypted bool
	Iv               sql.NullString
	Seq              uint64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.ParentID,
		arg.Type,
		arg.Content,
		arg.ContentEncrypted,
		arg.Iv,
		arg.Seq,
	)
	return err
}

const insertMessageReaction = `-- name: InsertMessageReaction :execrows
INSERT IGNORE INTO message_reactions (message_id, user_id, emoji)
VALUES (?, ?, ?)
`

type InsertMessageReactionParams struct {
	MessageID []byte
	UserID    []byte
	Emoji     string
}

// INSERT IGNORE: nếu đã react → affected = 0 → logic bỏ reaction
func (q *Queries) InsertMessageReaction(ctx context.Context, arg InsertMessageReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSystemMessage = `-- name: InsertSystemMessage :exec
INSERT INTO messages (id, conversation_id, sender_id, type, content, seq)
VALUES (?, ?, ?, 6, ?, ?)
`

type InsertSystemMessageParams struct {
	ID             []byte
	ConversationID []byte
	SenderID       []byte
	Content        sql.NullString
	Seq            uint64
}

// System message (type=6): member joined/left, group created, v.v.
func (q *Queries) InsertSystemMessage(ctx context.Context, arg InsertSystemMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertSystemMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
		arg.Seq,
	)
	return err
}

const listMessagesFirstPage = `-- name: ListMessagesFirstPage :many
SELECT id, conversation_id, sender_id, parent_id, type,
       content, content_encrypted, iv, seq,
       is_edited, is_deleted, deleted_at, created_at, updated_at
FROM messages
WHERE conversation_id = ? AND is_deleted = 0
ORDER BY created_at DESC, seq DESC
LIMIT ?
`

type ListMessagesFirstPageParams struct {
	ConversationID []byte
	Limit          int32
}

func (q *Queries) ListMessagesFirstPage(ctx context.Context, arg ListMessagesFirstPageParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesFirstPage, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.ParentID,
			&i.Type,
			&i.Content,
			&i.ContentEncrypted,
			&i.Iv,
			&i.Seq,
			&i.IsEdited,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesNextPage = `-- name: ListMessagesNextPage :many
SELECT id, conversation_id, sender_id, parent_id, type,
       content, content_encrypted, iv, seq,
       is_edited, is_deleted, deleted_at, created_at, updated_at
FROM messages
WHERE conversation_id = ?
  AND is_deleted = 0
  AND (created_at < ? OR (created_at = ? AND seq < ?))
ORDER BY created_at DESC, seq DESC
LIMIT ?
`

type ListMessagesNextPageParams struct {
	ConversationID []byte
	CreatedAt      time.Time
	CreatedAt_2    time.Time
	Seq            uint64
	Limit          int32
}

// Cursor pagination dùng (created_at, seq) — time trước thu hẹp phạm vi.
func (q *Queries) ListMessagesNextPage(ctx context.Context, arg ListMessagesNextPageParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesNextPage,
		arg.ConversationID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.ParentID,
			&i.Type,
			&i.Content,
			&i.ContentEncrypted,
			&i.Iv,
			&i.Seq,
			&i.IsEdited,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages
SET is_deleted = 1, deleted_at = NOW(), content = NULL, updated_at = NOW(3)
WHERE id = ? AND is_deleted = 0
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, softDeleteMessage, id)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :execrows
UPDATE messages
SET content = ?, is_edited = 1, updated_at = NOW(3)
WHERE id = ?
  AND sender_id = ?
  AND is_deleted = 0
  AND created_at > DATE_SUB(NOW(), INTERVAL 24 HOUR)
`

type UpdateMessageContentParams struct {
	Content  sql.NullString
	ID       []byte
	SenderID []byte
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMessageContent, arg.Content, arg.ID, arg.SenderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
