// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

// File đính kèm trong tin nhắn
type Attachment struct {
	// UUID v7 — BINARY(16)
	ID []byte
	// FK → messages.id
	MessageID []byte
	FileName  string
	// S3/CDN URL
	FileUrl  string
	MimeType string
	// [FIX #5] Kích thước byte — BIGINT tránh overflow file > 4GB
	FileSizeBytes uint64
	// [FIX #6] Pixels ảnh/video — MEDIUMINT max ~16.7M px
	Width sql.NullInt32
	// [FIX #6] Pixels ảnh/video — MEDIUMINT max ~16.7M px
	Height sql.NullInt32
	// Giây — audio hoặc video (SMALLINT max 65,535s ≈ 18h)
	DurationSec sql.NullInt16
	CreatedAt   time.Time
}

// Hội thoại — DM, nhóm hoặc channel
type Conversation struct {
	// UUID v7 — BINARY(16)
	ID []byte
	// 1=direct 2=group 3=channel — TINYINT tránh ALTER lock
	Type int8
	// Tên nhóm — NULL với DM
	Name        sql.NullString
	AvatarUrl   sql.NullString
	Description sql.NullString
	// FK → users.id — NULL khi user đã xóa tài khoản
	CreatedBy sql.NullString
	// Denormalized — NO FK — cập nhật qua Kafka worker
	LastMessageID sql.NullString
	// Sort danh sách conversation
	LastActivityAt *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Thành viên trong hội thoại
type ConversationMember struct {
	ID uint64
	// FK → conversations.id
	ConversationID []byte
	// FK → users.id
	UserID []byte
	// 1=owner 2=admin 3=member — TINYINT tránh ALTER lock
	Role int8
	// 1 = tắt thông báo
	IsMuted bool
	// Fallback watermark khi Redis miss hoặc message_status chưa backfill.
	//                                                                Cập nhật = MAX(ms.read_at) khi user đóng conversation.
	//                                                                KHÔNG dùng để đếm unread: dùng Redis unread:{uid}:{cid} hoặc message_status.
	LastReadAt *time.Time
	JoinedAt   time.Time
}

// Tin nhắn — core table
type Message struct {
	// UUID v7 — BINARY(16), timestamp prefix đảm bảo insert tuần tự
	ID []byte
	// FK → conversations.id
	ConversationID []byte
	// FK → users.id
	SenderID []byte
	// Reply/thread — self ref FK
	ParentID sql.NullString
	// 1=text 2=image 3=file 4=audio 5=video 6=system
	Type int8
	// Nội dung — MEDIUMTEXT ~16MB
	Content sql.NullString
	// 1 = nội dung đã AES-256 encrypt
	ContentEncrypted bool
	// AES Initialization Vector — 16 bytes hex-encoded
	Iv sql.NullString
	// Thứ tự trong conversation — tăng từ Redis INCR seq:{conv_id}
	Seq      uint64
	IsEdited bool
	// Soft delete flag
	IsDeleted bool
	// [BONUS] Thời điểm soft delete — cleanup job xóa khi deleted_at < NOW()-30d
	DeletedAt *time.Time
	// Millisecond precision
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Reaction emoji — Slack-style
type MessageReaction struct {
	ID uint64
	// FK → messages.id
	MessageID []byte
	// FK → users.id
	UserID []byte
	// Unicode emoji — vd: 👍 😂 🔥
	Emoji     string
	CreatedAt time.Time
}

// Trạng thái đọc — record tồn tại = đã đọc, không có record = chưa đọc
type MessageStatus struct {
	// FK → messages.id
	MessageID []byte
	// FK → users.id
	UserID []byte
	// [FIX #2] Thời điểm đọc — record tồn tại = đã đọc, không có record = chưa đọc
	ReadAt time.Time
}

// Danh bạ và trạng thái kết bạn
type UserContact struct {
	ID uint64
	// Người gửi lời mời — FK → users.id
	UserID []byte
	// Người nhận lời mời — FK → users.id
	ContactID []byte
	// 1=pending 2=accepted 3=blocked
	Status    int8
	CreatedAt time.Time
	UpdatedAt time.Time
}
