// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CreateConversation(ctx context.Context, arg CreateConversationParams) error
	DeleteConversationMember(ctx context.Context, arg DeleteConversationMemberParams) error
	DeleteMessageReaction(ctx context.Context, arg DeleteMessageReactionParams) error
	GetAttachmentsByMessageIDs(ctx context.Context, messageIds [][]byte) ([]Attachment, error)
	GetConversationByID(ctx context.Context, id []byte) (Conversation, error)
	GetConversationMember(ctx context.Context, arg GetConversationMemberParams) (ConversationMember, error)
	// Dùng để warm conv:members Redis cache
	GetConversationMemberIDs(ctx context.Context, conversationID []byte) ([][]byte, error)
	// Tìm DM đã tồn tại giữa 2 users — idempotent create
	GetDMConversation(ctx context.Context, arg GetDMConversationParams) ([]byte, error)
	// Xử lý conversation chưa có message (NULL → 0).
	GetMaxSeq(ctx context.Context, conversationID []byte) (int64, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int8, error)
	GetMessageByID(ctx context.Context, id []byte) (Message, error)
	GetMessageCursorTS(ctx context.Context, arg GetMessageCursorTSParams) (time.Time, error)
	GetReactionsByMessageIDs(ctx context.Context, messageIds [][]byte) ([]MessageReaction, error)
	GetUnreadCountByWatermark(ctx context.Context, arg GetUnreadCountByWatermarkParams) (int64, error)
	// Dùng khi WS connect: load toàn bộ conv user đang tham gia.
	GetUserConversationIDs(ctx context.Context, userID []byte) ([][]byte, error)
	InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error
	// INSERT IGNORE: user đã là member → bỏ qua, không lỗi.
	InsertConversationMember(ctx context.Context, arg InsertConversationMemberParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	// INSERT IGNORE: nếu đã react → affected = 0 → logic bỏ reaction
	InsertMessageReaction(ctx context.Context, arg InsertMessageReactionParams) (int64, error)
	// System message (type=6): member joined/left, group created, v.v.
	InsertSystemMessage(ctx context.Context, arg InsertSystemMessageParams) error
	ListConversationsFirstPage(ctx context.Context, arg ListConversationsFirstPageParams) ([]ListConversationsFirstPageRow, error)
	ListConversationsNextPage(ctx context.Context, arg ListConversationsNextPageParams) ([]ListConversationsNextPageRow, error)
	ListMessagesFirstPage(ctx context.Context, arg ListMessagesFirstPageParams) ([]Message, error)
	// Cursor pagination dùng (created_at, seq) — time trước thu hẹp phạm vi.
	ListMessagesNextPage(ctx context.Context, arg ListMessagesNextPageParams) ([]Message, error)
	SoftDeleteMessage(ctx context.Context, id []byte) error
	// Gọi bởi Kafka worker async sau khi gửi tin nhắn.
	UpdateConversationLastActivity(ctx context.Context, arg UpdateConversationLastActivityParams) error
	UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error
	UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
