// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: room.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations
    (id, type, name, avatar_url, description, created_by, last_activity_at)
VALUES (?, ?, ?, ?, ?, ?, NOW(3))
`

type CreateConversationParams struct {
	ID          []byte
	Type        int8
	Name        sql.NullString
	AvatarUrl   sql.NullString
	Description sql.NullString
	CreatedBy   sql.NullString
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.AvatarUrl,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}

const deleteConversationMember = `-- name: DeleteConversationMember :exec
DELETE FROM conversation_members
WHERE conversation_id = ? AND user_id = ?
`

type DeleteConversationMemberParams struct {
	ConversationID []byte
	UserID         []byte
}

func (q *Queries) DeleteConversationMember(ctx context.Context, arg DeleteConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, name, avatar_url, description, created_by,
       last_message_id, last_activity_at, created_at, updated_at
FROM conversations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetConversationByID(ctx context.Context, id []byte) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.Description,
		&i.CreatedBy,
		&i.LastMessageID,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMember = `-- name: GetConversationMember :one
SELECT id, conversation_id, user_id, role, is_muted, last_read_at, joined_at
FROM conversation_members
WHERE conversation_id = ? AND user_id = ?
LIMIT 1
`

type GetConversationMemberParams struct {
	ConversationID []byte
	UserID         []byte
}

func (q *Queries) GetConversationMember(ctx context.Context, arg GetConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRowContext(ctx, getConversationMember, arg.ConversationID, arg.UserID)
	var i ConversationMember
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.IsMuted,
		&i.LastReadAt,
		&i.JoinedAt,
	)
	return i, err
}

const getConversationMemberIDs = `-- name: GetConversationMemberIDs :many
SELECT user_id FROM conversation_members
WHERE conversation_id = ?
`

// Dùng để warm conv:members Redis cache
func (q *Queries) GetConversationMemberIDs(ctx context.Context, conversationID []byte) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMemberIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var user_id []byte
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDMConversation = `-- name: GetDMConversation :one
SELECT c.id
FROM conversations c
JOIN conversation_members m1
  ON m1.conversation_id = c.id AND m1.user_id = ?
JOIN conversation_members m2
  ON m2.conversation_id = c.id AND m2.user_id = ?
WHERE c.type = 1
LIMIT 1
`

type GetDMConversationParams struct {
	UserID   []byte
	UserID_2 []byte
}

// Tìm DM đã tồn tại giữa 2 users — idempotent create
func (q *Queries) GetDMConversation(ctx context.Context, arg GetDMConversationParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getDMConversation, arg.UserID, arg.UserID_2)
	var id []byte
	err := row.Scan(&id)
	return id, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM conversation_members
WHERE conversation_id = ? AND user_id = ?
LIMIT 1
`

type GetMemberRoleParams struct {
	ConversationID []byte
	UserID         []byte
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int8, error) {
	row := q.db.QueryRowContext(ctx, getMemberRole, arg.ConversationID, arg.UserID)
	var role int8
	err := row.Scan(&role)
	return role, err
}

const insertConversationMember = `-- name: InsertConversationMember :exec
INSERT IGNORE INTO conversation_members (conversation_id, user_id, role)
VALUES (?, ?, ?)
`

type InsertConversationMemberParams struct {
	ConversationID []byte
	UserID         []byte
	Role           int8
}

// INSERT IGNORE: user đã là member → bỏ qua, không lỗi.
func (q *Queries) InsertConversationMember(ctx context.Context, arg InsertConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertConversationMember, arg.ConversationID, arg.UserID, arg.Role)
	return err
}

const listConversationsFirstPage = `-- name: ListConversationsFirstPage :many
SELECT
    c.id, c.type, c.name, c.avatar_url,
    c.last_message_id, c.last_activity_at, c.created_at, c.updated_at,
    cm.role, cm.is_muted
FROM conversations c
INNER JOIN conversation_members cm
    ON cm.conversation_id = c.id AND cm.user_id = ?
ORDER BY c.last_activity_at DESC, c.id DESC
LIMIT ?
`

type ListConversationsFirstPageParams struct {
	UserID []byte
	Limit  int32
}

type ListConversationsFirstPageRow struct {
	ID             []byte
	Type           int8
	Name           sql.NullString
	AvatarUrl      sql.NullString
	LastMessageID  sql.NullString
	LastActivityAt *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Role           int8
	IsMuted        bool
}

func (q *Queries) ListConversationsFirstPage(ctx context.Context, arg ListConversationsFirstPageParams) ([]ListConversationsFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsFirstPage, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsFirstPageRow{}
	for rows.Next() {
		var i ListConversationsFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AvatarUrl,
			&i.LastMessageID,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.IsMuted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsNextPage = `-- name: ListConversationsNextPage :many
SELECT
    c.id, c.type, c.name, c.avatar_url,
    c.last_message_id, c.last_activity_at, c.created_at, c.updated_at,
    cm.role, cm.is_muted
FROM conversations c
INNER JOIN conversation_members cm
    ON cm.conversation_id = c.id AND cm.user_id = ? 
WHERE (c.last_activity_at < ? OR (c.last_activity_at = ? AND c.id < ?))
ORDER BY c.last_activity_at DESC, c.id DESC
LIMIT ?
`

type ListConversationsNextPageParams struct {
	UserID           []byte
	LastActivityAt   *time.Time
	LastActivityAt_2 *time.Time
	ID               []byte
	Limit            int32
}

type ListConversationsNextPageRow struct {
	ID             []byte
	Type           int8
	Name           sql.NullString
	AvatarUrl      sql.NullString
	LastMessageID  sql.NullString
	LastActivityAt *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Role           int8
	IsMuted        bool
}

func (q *Queries) ListConversationsNextPage(ctx context.Context, arg ListConversationsNextPageParams) ([]ListConversationsNextPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsNextPage,
		arg.UserID,
		arg.LastActivityAt,
		arg.LastActivityAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsNextPageRow{}
	for rows.Next() {
		var i ListConversationsNextPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AvatarUrl,
			&i.LastMessageID,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.IsMuted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationLastActivity = `-- name: UpdateConversationLastActivity :exec
UPDATE conversations
SET last_message_id = ?, last_activity_at = NOW(3), updated_at = NOW(3)
WHERE id = ?
`

type UpdateConversationLastActivityParams struct {
	LastMessageID sql.NullString
	ID            []byte
}

// Gọi bởi Kafka worker async sau khi gửi tin nhắn.
func (q *Queries) UpdateConversationLastActivity(ctx context.Context, arg UpdateConversationLastActivityParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationLastActivity, arg.LastMessageID, arg.ID)
	return err
}

const updateLastReadAt = `-- name: UpdateLastReadAt :exec
UPDATE conversation_members
SET    last_read_at = ?
WHERE  conversation_id = ?
  AND  user_id        = ?
  AND  (last_read_at IS NULL OR last_read_at < ?)
`

type UpdateLastReadAtParams struct {
	LastReadAt     *time.Time
	ConversationID []byte
	UserID         []byte
	LastReadAt_2   *time.Time
}

func (q *Queries) UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastReadAt,
		arg.LastReadAt,
		arg.ConversationID,
		arg.UserID,
		arg.LastReadAt_2,
	)
	return err
}
